<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <RootNamespace>Anunnaki.BL.Models</RootNamespace>
    <TargetFramework>net10.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Anunnaki.Base.Functionallity\Anunnaki.BL.Base.vbproj" />
    <ProjectReference Include="..\Anunnaki.Models.Base\Anunnaki.Models.Base.vbproj" />
  </ItemGroup>

</Project>
