<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows10.0.26100.0</TargetFramework>
    <StartupObject>Sub Main</StartupObject>
    <UseWindowsForms>true</UseWindowsForms>
    <MyType>WindowsForms</MyType>
    <SupportedOSPlatformVersion>7.0</SupportedOSPlatformVersion>
    <Authors>Croket</Authors>
    <Company>CroketWorld</Company>
    <Copyright>MIT</Copyright>
    <PackageReadmeFile>README.md</PackageReadmeFile>
    <RepositoryUrl>https://github.com/croketworld/CrearIcono</RepositoryUrl>
    <PackageTags>icon, stable diffusion, AI, generative AI, winforms, windows, python</PackageTags>
    <NeutralLanguage>es-ES</NeutralLanguage>
    <AnalysisLevel>latest-all</AnalysisLevel>
    <PackageId>CroketWorld.$(AssemblyName)</PackageId>
    <Title>Crear Icono - Croketworld</Title>
    <PackAsTool>False</PackAsTool>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
    <RegisterForComInterop>False</RegisterForComInterop>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|AnyCPU'">
    <RegisterForComInterop>False</RegisterForComInterop>
  </PropertyGroup>

  <ItemGroup>
    <Import Include="System.Data" />
    <Import Include="System.Drawing" />
    <Import Include="System.Windows.Forms" />
  </ItemGroup>

  <ItemGroup>
    <None Include="..\README.md">
      <Pack>True</Pack>
      <PackagePath>\</PackagePath>
    </None>
  </ItemGroup>

  <ItemGroup>
    <Compile Update="My Project\Application.Designer.vb">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>Application.myapp</DependentUpon>
    </Compile>
  </ItemGroup>

  <ItemGroup>
    <None Update="My Project\Application.myapp">
      <Generator>MyApplicationCodeGenerator</Generator>
      <LastGenOutput>Application.Designer.vb</LastGenOutput>
    </None>
  </ItemGroup>

</Project>